### ISSUE TITLE
unicode

### ISSUE THREAD

**Issue by okhmanyuk-ev** [d-mozulyov/CrystalLUA#1]
Господин, будут ли версии под юникодные делфи?

**Comment by d-mozulyov** [comment]
На данный момент проект заморожен. В планах и Unicode, и справочная система, и IDE, и новые возможности RTTI, даже рассматриваются варианты статичной линковки *.obj или JIT. Возобновление разработки возможно либо в случае серьёзного финансирования, либо в случае наличия как минимум 5 активных энтузиастов, которые возьмут на себя задачи ресёрча, написания тулсета и перевода текста справки на английский.

**Comment by zeal1209** [comment]
Печальные новости, ведь все новые делфи разрабатываются чисто юникодными - это значит, что ваша либа со временем потеряет всякую актуальность, ведь уже сейчас большинство сидит на студиях новее 2007 (мы ведь не берём в расчёт фанатиков, упёртых в седьмую делфи, я надеюсь?). По сути перевод на юникод не такой трудоёмкий (как правило). Самостоятельно пробовал заменить все String -> AnsiString, PChar -> PAnsiChar, LoadFromFile -> LoadFromFileA, etc.. но это ни к чему не привело. Судя по всему есть какие то нюансы, о которых знаете только вы. Будет весьма печально, если проект, которому сейчас нет аналогов, так и не получит развития...

**Comment by d-mozulyov** [comment]
Мне тоже печально, что при всей полезности и удобстве мало кто может вложить свои силы, время и финансы в развитие проекта. Мне остаётся лишь надеяться, что со временем такие люди появятся.

**Comment by d-mozulyov** [comment]
Текущая версия поддерживает Юникод
