### ISSUE TITLE
ELuaScript exception

### ISSUE THREAD

**Issue by yymsc** [d-mozulyov/CrystalLUA#3]
Hi,

I try to use CrystalLUA in my project but I get the attached exception when I try to run the first sample program.

![LUA exception](https://user-images.githubusercontent.com/4045703/128186156-4ec5f68c-7665-47b0-a42f-9230b44f2354.png)

I'm using Delphi 10.4 Update 2 and lua-5.2.4_Win32_bin.zip.

**Comment by d-mozulyov** [comment]
Unfortunately, the library does not support version 5.2.4. Try 5.2.1 or earlier.
