### ISSUE TITLE
Не вызываются глобальные функции.

### ISSUE THREAD

**Issue by KOTOEB** [d-mozulyov/CrystalLUA#4]
Здравствуйте. Написал вот такую функцию

procedure luaMBW(const AArgs: PLuaArgList; const AArguments: PLuaArguments);
var t,m:WideString;
begin
Form1.Caption:='';
m:=AArgs[0].AsString;
if Length(AArgs^)=1 then t:=AArgs[1].AsString else t:='';
MessageBoxW(0,PWideChar(m),PWideChar(t),0);
end;

пробовал так же такой вид

function luaMBW(const Args: TLuaArgs): TLuaArg;
var t,m:WideString;
begin
m:=Args.Items[0].AsString;
if Args.Count=2 then t:=Args.Items[1].AsString else t:='';
MessageBoxW(0,PWideChar(m),PWideChar(t),0);
end;

Создаю ЛУА вот так

procedure TForm1.FormCreate(Sender: TObject);
begin
Lua:=TLua.Create;
Lua.RegProc('mbw',@luaMBW,1,2);
end;

Активирую вот так

procedure TForm1.Button1Click(Sender: TObject);
var Text:WideString;
begin
Text:='mbw("123","456")';
Lua.RunScript(Text);
end;

И при нажатии на Button1 не происходит вообще ничего. Дебагер в функцию luaMBW вообще не заходит. При этом добавление и изменение глобальных переменных работает, я протестировал изменение глобального интегера.

Что я делаю не так? (Использую Delphi 7)

**Comment by d-mozulyov** [comment]
> Что я делаю не так? (Использую Delphi 7)

Всё так. Просто глобальные функции на данный момент не реализованы
